# Generated by Django 3.1.5 on 2021-12-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('intern', 'intern'), ('hr', 'hr'), ('manager', 'manager'), ('developer', 'developer')], default='intern', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('emp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapi.employee')),
            ],
        ),
    ]
