# Generated by Django 3.1.5 on 2021-12-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeeapi', '0002_auto_20211212_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uname',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
